<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function meeting_autogen_hook_name() {
	return 'meeting_autogen_cron';
}

function meeting_autogen_bootstrap() {
	if ( ! meeting_autogen_enabled() ) {
		wp_clear_scheduled_hook( meeting_autogen_hook_name() );
		return;
	}

	if ( ! wp_next_scheduled( meeting_autogen_hook_name() ) ) {
		wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', meeting_autogen_hook_name() );
	}
}

function meeting_autogen_enabled() {
	$settings = Meeting_Reminder_Settings::get();

	return ! empty( $settings['enable_event_autogeneration'] );
}

function meeting_autogen_maybe_migrate_content() {
	if ( ! meeting_autogen_enabled() ) {
		return;
	}

	$option_key = 'meeting_autogen_content_migration_v2';

	if ( get_option( $option_key ) ) {
		return;
	}

	if ( ! post_type_exists( 'tribe_events' ) ) {
		return;
	}

	$config         = meeting_autogen_defaults();
	$legacy_content = meeting_autogen_legacy_content();
	$query          = new WP_Query(
		array(
			'post_type'      => 'tribe_events',
			'post_status'    => array( 'publish', 'future', 'draft', 'pending', 'private' ),
			'posts_per_page' => -1,
			'fields'         => 'ids',
			'meta_query'     => array(
				'relation' => 'OR',
				array(
					'key'   => '_cso_autogen_source',
					'value' => 'meeting_reminder',
				),
				array(
					'key'   => '_cso_autogenerated',
					'value' => '1',
				),
			),
		)
	);

	if ( empty( $query->posts ) ) {
		update_option( $option_key, 1, false );
		return;
	}

	foreach ( $query->posts as $event_id ) {
		$current_post = get_post( $event_id );

		if ( ! $current_post instanceof WP_Post ) {
			continue;
		}

		$current_content = trim( (string) $current_post->post_content );
		$matches_legacy  = in_array(
			$current_content,
			array(
				trim( $legacy_content ),
				trim( meeting_autogen_plain_content() ),
			),
			true
		);

		if ( ! $matches_legacy ) {
			continue;
		}

		$updated = wp_update_post(
			array(
				'ID'           => $event_id,
				'post_content' => $config['content'],
			),
			true
		);

		if ( is_wp_error( $updated ) ) {
			meeting_autogen_log(
				'Failed to migrate autogenerated event content.',
				array(
					'event_id' => $event_id,
					'error'    => $updated->get_error_message(),
				)
			);
			continue;
		}

		delete_post_meta( $event_id, '_EventURL' );

		meeting_autogen_log(
			'Migrated autogenerated event content to the HTML template and removed website meta.',
			array(
				'event_id' => $event_id,
			)
		);
	}

	update_option( $option_key, 1, false );
}

function meeting_autogen_cleanup_legacy_slug_meta() {
	if ( ! meeting_autogen_enabled() ) {
		return;
	}

	$option_key = 'meeting_autogen_legacy_slug_cleanup_v1';

	if ( get_option( $option_key ) ) {
		return;
	}

	if ( ! post_type_exists( 'tribe_events' ) ) {
		return;
	}

	$query = new WP_Query(
		array(
			'post_type'      => 'tribe_events',
			'post_status'    => array( 'publish', 'future', 'draft', 'pending', 'private' ),
			'posts_per_page' => -1,
			'fields'         => 'ids',
			'meta_query'     => array(
				array(
					'key'     => '_cso_autogen_legacy_slug',
					'compare' => 'EXISTS',
				),
			),
		)
	);

	if ( ! empty( $query->posts ) ) {
		foreach ( $query->posts as $event_id ) {
			delete_post_meta( $event_id, '_cso_autogen_legacy_slug' );
		}
	}

	delete_option( 'meeting_autogen_slug_migration_v1' );
	update_option( $option_key, 1, false );
}

function meeting_autogen_defaults() {
	$settings  = Meeting_Reminder_Settings::get();
	$zoom_link = isset( $settings['autogen_zoom_link'] ) ? (string) $settings['autogen_zoom_link'] : '';
	$zoom_id   = isset( $settings['autogen_zoom_id'] ) ? (string) $settings['autogen_zoom_id'] : '';
	$passcode  = isset( $settings['autogen_zoom_passcode'] ) ? (string) $settings['autogen_zoom_passcode'] : '';
	$meta      = array();

	if ( '' !== $zoom_link ) {
		$meta['_cso_zoom_link'] = $zoom_link;
	}

	if ( '' !== $zoom_id ) {
		$meta['_cso_zoom_id'] = $zoom_id;
	}

	if ( '' !== $passcode ) {
		$meta['_cso_zoom_passcode'] = $passcode;
	}

	$config = array(
		'title'         => isset( $settings['autogen_event_title'] ) && '' !== $settings['autogen_event_title'] ? (string) $settings['autogen_event_title'] : 'Central Service Office Monthly Committee Meeting',
		'content'       => meeting_autogen_html_content(),
		'start_time'    => isset( $settings['autogen_start_time'] ) ? (string) $settings['autogen_start_time'] : '16:30',
		'duration'      => isset( $settings['autogen_duration_minutes'] ) ? absint( $settings['autogen_duration_minutes'] ) : 60,
		'zoom_link'     => $zoom_link,
		'zoom_id'       => $zoom_id,
		'zoom_passcode' => $passcode,
		'meta'          => $meta,
	);

	return apply_filters( 'meeting_autogen_defaults', $config );
}

function meeting_autogen_legacy_content() {
	return "Hi all,\n\nThis monthly CSO Committee meeting is scheduled online.";
}

function meeting_autogen_plain_content() {
	return 'This monthly CSO Committee meeting is scheduled online.';
}

function meeting_autogen_html_content() {
	$settings  = Meeting_Reminder_Settings::get();
	$zoom_link = isset( $settings['autogen_zoom_link'] ) ? (string) $settings['autogen_zoom_link'] : '';
	$zoom_id   = isset( $settings['autogen_zoom_id'] ) ? (string) $settings['autogen_zoom_id'] : '';
	$passcode  = isset( $settings['autogen_zoom_passcode'] ) ? (string) $settings['autogen_zoom_passcode'] : '';

	$content = '<p>This monthly CSO Committee meeting is scheduled online.</p>';

	if ( '' === $zoom_link && '' === $zoom_id && '' === $passcode ) {
		return $content;
	}

	$content .= '<p><strong>Zoom details:</strong></p><p>';
	$details  = array();

	if ( '' !== $zoom_link ) {
		$details[] = '<strong>Link:</strong> <a href="' . esc_url( $zoom_link ) . '">' . esc_html( $zoom_link ) . '</a>';
	}

	if ( '' !== $zoom_id ) {
		$details[] = '<strong>Meeting ID:</strong> ' . esc_html( $zoom_id );
	}

	if ( '' !== $passcode ) {
		$details[] = '<strong>Passcode:</strong> ' . esc_html( $passcode );
	}

	return $content . implode( '<br />', $details ) . '</p>';
}

function meeting_autogen_run() {
	if ( ! meeting_autogen_enabled() ) {
		wp_clear_scheduled_hook( meeting_autogen_hook_name() );
		return;
	}

	if ( ! post_type_exists( 'tribe_events' ) ) {
		meeting_autogen_log( 'TEC event post type is not registered; autogeneration skipped.' );
		return;
	}

	$config = meeting_autogen_defaults();
	$now    = new DateTimeImmutable( 'now', wp_timezone() );

	for ( $offset = 0; $offset < 12; $offset++ ) {
		$target_month = $now->modify( 'first day of this month' )->modify( '+' . $offset . ' months' );
		$month_key    = $target_month->format( 'Y-m' );
		$schedule     = meeting_autogen_build_schedule( $target_month, $config );

		if ( is_wp_error( $schedule ) ) {
			meeting_autogen_log( 'Failed to build schedule.', array( 'month' => $month_key, 'error' => $schedule->get_error_message() ) );
			continue;
		}

		if ( 0 === $offset && $schedule['end_local'] < $now ) {
			continue;
		}

		if ( meeting_autogen_state_exists( $month_key ) ) {
			continue;
		}

		$existing_event_id = meeting_autogen_find_existing_event( $month_key, $schedule, $config );

		if ( $existing_event_id ) {
			meeting_autogen_write_state( $month_key, $existing_event_id, $schedule['start_utc']->format( 'Y-m-d H:i:s' ), 'linked_existing' );
			continue;
		}

		$event_id = meeting_autogen_create_event( $month_key, $schedule, $config );

		if ( ! $event_id ) {
			continue;
		}

		meeting_autogen_write_state( $month_key, $event_id, $schedule['start_utc']->format( 'Y-m-d H:i:s' ), 'created' );
	}
}

function meeting_autogen_build_schedule( DateTimeImmutable $month, $config ) {
	$first_day      = $month->setTime( 0, 0, 0 );
	$first_saturday = '6' === $first_day->format( 'w' ) ? $first_day : $first_day->modify( 'next saturday' );
	$time_parts     = explode( ':', (string) $config['start_time'] );

	if ( count( $time_parts ) < 2 ) {
		return new WP_Error( 'meeting_autogen_bad_time', __( 'The autogeneration start time is invalid.', 'cso-meeting-reminder' ) );
	}

	$start_local = $first_saturday->setTime( (int) $time_parts[0], (int) $time_parts[1], isset( $time_parts[2] ) ? (int) $time_parts[2] : 0 );
	$end_local   = $start_local->add( new DateInterval( 'PT' . max( 1, absint( $config['duration'] ) ) . 'M' ) );

	return array(
		'month_key'   => $month->format( 'Y-m' ),
		'start_local' => $start_local,
		'end_local'   => $end_local,
		'start_utc'   => $start_local->setTimezone( new DateTimeZone( 'UTC' ) ),
		'end_utc'     => $end_local->setTimezone( new DateTimeZone( 'UTC' ) ),
	);
}

function meeting_autogen_state_exists( $month_key ) {
	global $wpdb;

	$table        = $wpdb->prefix . 'meeting_reminder_state';
	$reminder_key = meeting_autogen_reminder_key( $month_key );
	$existing     = $wpdb->get_var(
		$wpdb->prepare(
			"SELECT id FROM {$table} WHERE reminder_key = %s LIMIT 1",
			$reminder_key
		)
	);

	return ! empty( $existing );
}

function meeting_autogen_find_existing_event( $month_key, $schedule, $config ) {
	$day_start = $schedule['start_local']->format( 'Y-m-d 00:00:00' );
	$day_end   = $schedule['start_local']->format( 'Y-m-d 23:59:59' );

	$query = new WP_Query(
		array(
			'post_type'      => 'tribe_events',
			'post_status'    => array( 'publish', 'future', 'draft', 'pending', 'private' ),
			'posts_per_page' => 10,
			'fields'         => 'ids',
			'meta_query'     => array(
				array(
					'key'     => '_EventStartDate',
					'value'   => array( $day_start, $day_end ),
					'compare' => 'BETWEEN',
					'type'    => 'DATETIME',
				),
			),
		)
	);

	if ( empty( $query->posts ) ) {
		return 0;
	}

	foreach ( $query->posts as $event_id ) {
		$title      = get_the_title( $event_id );
		$month_meta = get_post_meta( $event_id, '_cso_autogen_month', true );

		if ( $month_meta === $month_key || $title === $config['title'] ) {
			return (int) $event_id;
		}
	}

	return 0;
}

function meeting_autogen_create_event( $month_key, $schedule, $config ) {
	$slug = meeting_autogen_slug( $schedule['start_local'] );

	$postarr = array(
		'post_type'    => 'tribe_events',
		'post_status'  => 'publish',
		'post_title'   => $config['title'],
		'post_content' => $config['content'],
		'post_name'    => $slug,
	);

	$event_id = wp_insert_post( wp_slash( $postarr ), true );

	if ( is_wp_error( $event_id ) || ! $event_id ) {
		meeting_autogen_log(
			'Failed to create autogenerated CSO meeting event.',
			array(
				'month' => $month_key,
				'error' => is_wp_error( $event_id ) ? $event_id->get_error_message() : 'Unknown insert failure',
			)
		);

		return 0;
	}

	$timezone = wp_timezone_string();
	$meta     = array(
		'_EventStartDate'      => $schedule['start_local']->format( 'Y-m-d H:i:s' ),
		'_EventEndDate'        => $schedule['end_local']->format( 'Y-m-d H:i:s' ),
		'_EventStartDateUTC'   => $schedule['start_utc']->format( 'Y-m-d H:i:s' ),
		'_EventEndDateUTC'     => $schedule['end_utc']->format( 'Y-m-d H:i:s' ),
		'_EventTimezone'       => $timezone ? $timezone : 'UTC',
		'_EventAllDay'         => 'no',
		'_EventShowMap'        => '0',
		'_EventShowMapLink'    => '0',
		'_cso_autogenerated'   => '1',
		'_cso_autogen_month'   => $month_key,
		'_cso_autogen_source'  => 'meeting_reminder',
		'_cso_event_duration'  => (string) absint( $config['duration'] ),
	);

	if ( ! empty( $config['meta'] ) && is_array( $config['meta'] ) ) {
		$meta = array_merge( $meta, $config['meta'] );
	}

	foreach ( $meta as $meta_key => $meta_value ) {
		update_post_meta( $event_id, $meta_key, $meta_value );
	}

	meeting_autogen_log(
		'Created autogenerated CSO meeting event.',
		array(
			'month'    => $month_key,
			'event_id' => $event_id,
		)
	);

	return (int) $event_id;
}

function meeting_autogen_slug( DateTimeImmutable $date ) {
	$month = strtolower( $date->format( 'F' ) );
	$year  = $date->format( 'Y' );

	return sanitize_title( 'CSO Meeting ' . $month . ' ' . $year );
}

function meeting_autogen_hide_frontend_details() {
	if ( ! is_singular( 'tribe_events' ) ) {
		return;
	}

	$post_id = get_queried_object_id();

	if ( ! $post_id || '1' !== (string) get_post_meta( $post_id, '_cso_autogenerated', true ) ) {
		return;
	}

	echo '<style id="cso-meeting-autogen-single-css">.tribe-events-single-section.tribe-events-event-meta,.tribe-events-event-meta{display:none !important;}</style>';
}

function meeting_autogen_write_state( $month_key, $event_id, $event_start_utc, $action ) {
	global $wpdb;

	$table = $wpdb->prefix . 'meeting_reminder_state';
	$ok    = $wpdb->insert(
		$table,
		array(
			'event_id'        => (string) $event_id,
			'reminder_key'    => meeting_autogen_reminder_key( $month_key ),
			'sent_at_gmt'     => current_time( 'mysql', true ),
			'event_start_utc' => $event_start_utc,
			'recipient_hash'  => null,
			'payload'         => wp_json_encode(
				array(
					'source' => 'meeting_reminder',
					'type'   => 'meeting_autogen',
					'month'  => $month_key,
					'action' => $action,
				)
			),
		),
		array( '%s', '%s', '%s', '%s', '%s', '%s' )
	);

	if ( false === $ok ) {
		meeting_autogen_log(
			'Failed to write autogeneration state.',
			array(
				'month'    => $month_key,
				'event_id' => $event_id,
				'action'   => $action,
				'db_error' => $wpdb->last_error,
			)
		);
	}
}

function meeting_autogen_reminder_key( $month_key ) {
	return 'autogen-' . preg_replace( '/[^0-9\-]/', '', (string) $month_key );
}

function meeting_autogen_log( $message, $context = array() ) {
	$serialized = ! empty( $context ) ? ' ' . wp_json_encode( $context ) : '';
	error_log( '[CSO Meeting Autogen] ' . $message . $serialized );

	if ( class_exists( 'Meeting_Reminder_Logger' ) ) {
		$logger = new Meeting_Reminder_Logger();
		$logger->log( 'info', $message, $context );
	}
}

add_action( 'init', 'meeting_autogen_bootstrap' );
add_action( 'init', 'meeting_autogen_maybe_migrate_content', 20 );
add_action( 'init', 'meeting_autogen_cleanup_legacy_slug_meta', 21 );
add_action( meeting_autogen_hook_name(), 'meeting_autogen_run' );
add_action( 'wp_head', 'meeting_autogen_hide_frontend_details' );
